### ISSUE TITLE
All versions yanked from rubygems

### ISSUE THREAD

**Issue by msmith-hpe** [chef/chef-api#69]
Just noticed that all of the released versions have been yanked from rubygems... 

Is there a reason for that?

**Comment by santosgian28** [comment]
Same here, can we tag @sethvargo ?

**Comment by phoolish** [comment]
https://github.com/sethvargo/chef-sugar

**Comment by leestran1995** [comment]
https://www.vice.com/en_us/article/mbm3xn/chef-sugar-author-deletes-code-sold-to-ice-immigration-customs-enforcement

**Comment by jrochkind** [comment]
I don't understand what exactly has happened, but see https://blog.rubygems.org/2019/09/20/chef-ownership.html

**Comment by Doltair** [comment]
hmm okay, so means we can grab the gem now? though v0.9.0 still forbidden
```
Gem::RemoteFetcher::FetchError bad response Forbidden 403 (https://rubygems.org/gems/chef-api-0.9.0.gem)
```

v0.8.0 is good

**Comment by geewiz** [comment]
> I don't understand what exactly has happened, but see https://blog.rubygems.org/2019/09/20/chef-ownership.html

Which I assume is a consequence of this: https://d.pr/i/n97cnX

**Comment by Doltair** [comment]
True @geewiz. We had ours working on v0.8.0 at the moment. And yeah totally 🙏 that this get resolved soon and hopefully to get the latest stable built gem.

**Comment by rmoriz** [comment]
While the gem was restored on rubygems, the source of the runtime dependency [logify]( https://rubygems.org/gems/logify) was deleted from github.

**Comment by Doltair** [comment]
Tagging @chef

**Comment by btm** [comment]
@rmoriz @Doltair, you can get the source here if you need it: http://deb.debian.org/debian/pool/main/r/ruby-logify/ruby-logify_0.2.0.orig.tar.gz

 https://github.com/chef/stove/issues/138 was our standing plan. Thanks for creating the issues @rmoriz.
